export interface AIMessage {
    id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    timestamp: number;
}

export const getLiveAIResponse = async (
    messages: { role: string; content: string }[],
    apiKey: string
): Promise<string> => {
    if (!apiKey) {
        throw new Error('API key is missing.');
    }

    // Default to Groq API endpoint
    const endpoint = 'https://api.groq.com/openai/v1/chat/completions';
    
    // If the user happens to provide an xAI key (gsk_), we can try to route it.
    // However, Groq also uses 'gsk_'. We will stick to Groq's endpoint for now.
    
    try {
        const response = await fetch(endpoint, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: 'llama-3.3-70b-versatile', // Updated from decommissioned llama3-8b-8192
                messages: [
                    { role: 'system', content: 'You are an advanced, helpful AI assistant built directly into NotepadX. You help users summarize notes, fix grammar, write content, and brainstorm. Be concise and professional.' },
                    ...messages
                ],
                temperature: 0.7,
                max_tokens: 1024,
            }),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => null);
            throw new Error(errorData?.error?.message || `API Error: ${response.status} ${response.statusText}`);
        }

        const data = await response.json();
        
        if (data.choices && data.choices.length > 0) {
            return data.choices[0].message.content;
        } else {
            throw new Error('No response generated by the AI.');
        }
    } catch (error: any) {
        console.error('AI API Error:', error);
        throw error;
    }
};
